# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: adamllwilliams
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: findbot-ig-importer
# "service" is the name of this project. This will also be added to your AWS resource names.
service: findbot-ig-importer

provider:
  name: aws
  runtime: nodejs24.x
  region: eu-west-2
  environment:
    APIFY_TOKEN: ${env:APIFY_TOKEN}
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

build:
  esbuild:
    format: esm
    external:
      - proxy-agent

functions:
  handler:
    handler: src/handler.importPost
    timeout: 60
    url:
      authorizer: 'aws_iam'
